//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanionBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanionBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action Required! ähnelt.
        /// </summary>
        internal static string actionRequired {
            get {
                return ResourceManager.GetString("actionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address: ähnelt.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creations ähnelt.
        /// </summary>
        internal static string creations {
            get {
                return ResourceManager.GetString("creations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current bot status ähnelt.
        /// </summary>
        internal static string currentBotState {
            get {
                return ResourceManager.GetString("currentBotState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The bot is currently in {0} servers.
        ///Not yet processed data: ähnelt.
        /// </summary>
        internal static string currentlyXServers {
            get {
                return ResourceManager.GetString("currentlyXServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data by PNavCopy ähnelt.
        /// </summary>
        internal static string dataByBot {
            get {
                return ResourceManager.GetString("dataByBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download of attached file failed: {0} ähnelt.
        /// </summary>
        internal static string downloadFailed {
            get {
                return ResourceManager.GetString("downloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the correct location. If you are not sure, let it time out.
        ///The following info is available: ähnelt.
        /// </summary>
        internal static string editMultiMatches {
            get {
                return ResourceManager.GetString("editMultiMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edits ähnelt.
        /// </summary>
        internal static string edits {
            get {
                return ResourceManager.GetString("edits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edits: ähnelt.
        /// </summary>
        internal static string edits_ {
            get {
                return ResourceManager.GetString("edits:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die use /pause or /resume commands to manage the import ähnelt.
        /// </summary>
        internal static string embedFooter {
            get {
                return ResourceManager.GetString("embedFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Too many or few parameters. ⚠
        ///Error message:
        ///```{0}```
        ///Please contact the bot owner by opening an issue at [GitHub](https://github.com/MaxEtMoritz/PNavCopy), providing what you did and which parameters you specified. ähnelt.
        /// </summary>
        internal static string errorBadArgs {
            get {
                return ResourceManager.GetString("errorBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ One or more parameters could not be converted. ⚠
        ///Error message:
        ///```{0}```
        ///Please check your parameters.
        ///If they seem correct, open up an issue at [GitHub](https://github.com/MaxEtMoritz/PNavCopy), providing what you did, which parameters you entered and what the error message was. ähnelt.
        /// </summary>
        internal static string ErrorConvertFailed {
            get {
                return ResourceManager.GetString("ErrorConvertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Internal Error. ⚠
        ///The bot has encountered a problem while executing this interaction. If the error persists, please open an issue at [GitHub](https://github.com/MaxEtMoritz/PNavCopy), providing as much information as possible.
        ///This Error message will (hopefully😅) help the developer investigate:
        ///```{0}``` ähnelt.
        /// </summary>
        internal static string errorException {
            get {
                return ResourceManager.GetString("errorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Internal Error. ⚠
        ///The bot has encountered a problem while executing this interaction. If the error persists, please open an issue at [GitHub](https://github.com/MaxEtMoritz/PNavCopy), providing as much information as possible.
        ///This Error message will (hopefully😅) help the developer investigate:
        ///```{0}``` ähnelt.
        /// </summary>
        internal static string errorParseFailed {
            get {
                return ResourceManager.GetString("errorParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Unknown interaction. ⚠
        ///Please contact the bot owner by opening an issue at [GitHub](https://github.com/MaxEtMoritz/PNavCopy), providing what you were trying to do when getting this error. ähnelt.
        /// </summary>
        internal static string ErrorUnknownCommand {
            get {
                return ResourceManager.GetString("ErrorUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnecting now. Goodbye! ähnelt.
        /// </summary>
        internal static string goodbye {
            get {
                return ResourceManager.GetString("goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guild ID ähnelt.
        /// </summary>
        internal static string guildId {
            get {
                return ResourceManager.GetString("guildId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Importing... ähnelt.
        /// </summary>
        internal static string importing {
            get {
                return ResourceManager.GetString("importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ❌ This interaction failed. ❌
        ///Reason: {0} ähnelt.
        /// </summary>
        internal static string interactionUnsuccessful {
            get {
                return ResourceManager.GetString("interactionUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid command structure: {0}. ähnelt.
        /// </summary>
        internal static string invalidCommandStructure {
            get {
                return ResourceManager.GetString("invalidCommandStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while parsing file: {0} ähnelt.
        /// </summary>
        internal static string jsonParsingFailed {
            get {
                return ResourceManager.GetString("jsonParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: Parsing of PokeNav ID failed. ähnelt.
        /// </summary>
        internal static string locationIdParseFailed {
            get {
                return ResourceManager.GetString("locationIdParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Did not receive a Response from PokeNav in time.
        ///Make sure PokeNav is able to respond in the Channel where you execute the command. ähnelt.
        /// </summary>
        internal static string modChannelFail {
            get {
                return ResourceManager.GetString("modChannelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There was a problem with the mod-channel. Try to run `/mod-channel` and then `/resume` to try again. ähnelt.
        /// </summary>
        internal static string modChannelProblem {
            get {
                return ResourceManager.GetString("modChannelProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Moderation channel successfully set to &lt;#{0}&gt; ähnelt.
        /// </summary>
        internal static string modChannelSuccess {
            get {
                return ResourceManager.GetString("modChannelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PokeNav Moderation Channel not set yet. Run `/mod-channel` to set it, then run `/resume` to create the PoI. ähnelt.
        /// </summary>
        internal static string modChannelUnset {
            get {
                return ResourceManager.GetString("modChannelUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message History permission missing. Unable to handle location select dialog =&gt; edit skipped. ähnelt.
        /// </summary>
        internal static string noMsgHistoryPerm {
            get {
                return ResourceManager.GetString("noMsgHistoryPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # creations ähnelt.
        /// </summary>
        internal static string numCreations {
            get {
                return ResourceManager.GetString("numCreations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die # edits ähnelt.
        /// </summary>
        internal static string numEdits {
            get {
                return ResourceManager.GetString("numEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Too few or too many parameters.
        ///Expected {0} to {1}. ähnelt.
        /// </summary>
        internal static string parameterMismatch {
            get {
                return ResourceManager.GetString("parameterMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are multiple matches for one or more parameters. Please refine your query.
        ///```{0}``` ähnelt.
        /// </summary>
        internal static string parameterMultiMatches {
            get {
                return ResourceManager.GetString("parameterMultiMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not parse Command parameter(s): {0}. ähnelt.
        /// </summary>
        internal static string paramParseFailed {
            get {
                return ResourceManager.GetString("paramParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paused ähnelt.
        /// </summary>
        internal static string paused {
            get {
                return ResourceManager.GetString("paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ❌ Error while pausing ähnelt.
        /// </summary>
        internal static string pauseError {
            get {
                return ResourceManager.GetString("pauseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⏸ Pausing, please be patient... ähnelt.
        /// </summary>
        internal static string pauseInProgress {
            get {
                return ResourceManager.GetString("pauseInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ℹ Nothing to Pause here, no Bulk Import running at the moment. ähnelt.
        /// </summary>
        internal static string pauseNoOp {
            get {
                return ResourceManager.GetString("pauseNoOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ✅ Successfully paused! ähnelt.
        /// </summary>
        internal static string pauseSuccessful {
            get {
                return ResourceManager.GetString("pauseSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Failed. PoI not found. ähnelt.
        /// </summary>
        internal static string poiNotFound {
            get {
                return ResourceManager.GetString("poiNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PokeNav did not respond in time. Please try again manually. ähnelt.
        /// </summary>
        internal static string pokeNavTimeout {
            get {
                return ResourceManager.GetString("pokeNavTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PokeNav did not update the select message in time, please try again manually. ähnelt.
        /// </summary>
        internal static string pokeNavUpdateTimeout {
            get {
                return ResourceManager.GetString("pokeNavUpdateTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Probably finished {0} ähnelt.
        /// </summary>
        internal static string probablyFinished {
            get {
                return ResourceManager.GetString("probablyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Attention! ⚠ The Bot is missing permissions in the PokeNav mod-channel:
        ///	{0} View Channel
        ///	{1} Send Messages
        ///	{2} Add Reactions (recommended but optional)
        ///	{3} View message history (for ambiguous edits)
        ///Make sure to grant the neccessary permissions for the bot for &lt;#{4}&gt;. ähnelt.
        /// </summary>
        internal static string promptMissingPerms {
            get {
                return ResourceManager.GetString("promptMissingPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No one reacted. Please try again manually. ähnelt.
        /// </summary>
        internal static string reactTimeout {
            get {
                return ResourceManager.GetString("reactTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ▶ Continuing... ähnelt.
        /// </summary>
        internal static string resume {
            get {
                return ResourceManager.GetString("resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ℹ Bulk import is already running, no need to resume. ähnelt.
        /// </summary>
        internal static string resumeAlreadyRunning {
            get {
                return ResourceManager.GetString("resumeAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die /resume to see prediction ähnelt.
        /// </summary>
        internal static string resumeForPrediction {
            get {
                return ResourceManager.GetString("resumeForPrediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ℹ No data to import present. ähnelt.
        /// </summary>
        internal static string resumeNoOp {
            get {
                return ResourceManager.GetString("resumeNoOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Head to &lt;#{0}&gt; and select the right location! ähnelt.
        /// </summary>
        internal static string selectRightLocation {
            get {
                return ResourceManager.GetString("selectRightLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is still to do: ähnelt.
        /// </summary>
        internal static string stillToDo {
            get {
                return ResourceManager.GetString("stillToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you really sure? The bot will need manual restart if you do this! ähnelt.
        /// </summary>
        internal static string sure {
            get {
                return ResourceManager.GetString("sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///This is the test instance. ähnelt.
        /// </summary>
        internal static string testInstance {
            get {
                return ResourceManager.GetString("testInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Internal Error. ⚠
        ///The bot has encountered a problem while executing this command. If the error persists, please open a GitHub issue at https://github.com/MaxEtMoritz/PNavCopy, providing as much information as possible.
        ///This Error message will (hopefully😅) help the developer investigate:
        ///```{0}``` ähnelt.
        /// </summary>
        internal static string textCommandException {
            get {
                return ResourceManager.GetString("textCommandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This command failed: {0}. ähnelt.
        /// </summary>
        internal static string textCommandUnsuccessful {
            get {
                return ResourceManager.GetString("textCommandUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time remaining ähnelt.
        /// </summary>
        internal static string timeRemaining {
            get {
                return ResourceManager.GetString("timeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type: ähnelt.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ❌ This interaction is not allowed in the current context. ❌
        ///{0} ähnelt.
        /// </summary>
        internal static string unmetPrecondition {
            get {
                return ResourceManager.GetString("unmetPrecondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This command is not allowed in the current context: {0}. ähnelt.
        /// </summary>
        internal static string unmetPreconditionTextBased {
            get {
                return ResourceManager.GetString("unmetPreconditionTextBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes i am ähnelt.
        /// </summary>
        internal static string yesIAm {
            get {
                return ResourceManager.GetString("yesIAm", resourceCulture);
            }
        }
    }
}
