//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanionBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CompanionBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Too many or few parameters. ⚠\nError message:\n```{0}```\nPlease contact the bot owner by opening an issue at [GitHub](https://github.com/MaxEtMoritz/PNavCopy), providing what you did and which parameters you specified. ähnelt.
        /// </summary>
        internal static string errorBadArgs {
            get {
                return ResourceManager.GetString("errorBadArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ One or more parameters could not be converted. ⚠\nError message:\n```{0}```\nPlease check your parameters.\nIf they seem correct, open up an issue at [GitHub](https://github.com/MaxEtMoritz/PNavCopy), providing what you did, which parameters you entered and what the error message was. ähnelt.
        /// </summary>
        internal static string ErrorConvertFailed {
            get {
                return ResourceManager.GetString("ErrorConvertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Internal Error. ⚠\nThe bot has encountered a problem while executing this interaction. If the error persists, please open an issue at [GitHub](https://github.com/MaxEtMoritz/PNavCopy), providing as much information as possible.\nThis Error message will (hopefully😅) help the developer investigate:\n```{0}``` ähnelt.
        /// </summary>
        internal static string errorException {
            get {
                return ResourceManager.GetString("errorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Internal Error. ⚠\nThe bot has encountered a problem while executing this interaction. If the error persists, please open an issue at [GitHub](https://github.com/MaxEtMoritz/PNavCopy), providing as much information as possible.\nThis Error message will (hopefully😅) help the developer investigate:\n```{0}``` ähnelt.
        /// </summary>
        internal static string errorParseFailed {
            get {
                return ResourceManager.GetString("errorParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Unknown interaction. ⚠\nPlease contact the bot owner by opening an issue at [GitHub](https://github.com/MaxEtMoritz/PNavCopy), providing what you were trying to do when getting this error. ähnelt.
        /// </summary>
        internal static string ErrorUnknownCommand {
            get {
                return ResourceManager.GetString("ErrorUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnecting now. Goodbye! ähnelt.
        /// </summary>
        internal static string goodbye {
            get {
                return ResourceManager.GetString("goodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ❌ This interaction failed. ❌\nReason: {0} ähnelt.
        /// </summary>
        internal static string interactionUnsuccessful {
            get {
                return ResourceManager.GetString("interactionUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Did not receive a Response from PokeNav in time!\nMake sure PokeNav is able to respond in the Channel where you execute the command! ähnelt.
        /// </summary>
        internal static string modChannelFail {
            get {
                return ResourceManager.GetString("modChannelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Moderation channel successfully set to &lt;#{0}&gt; ähnelt.
        /// </summary>
        internal static string modChannelSuccess {
            get {
                return ResourceManager.GetString("modChannelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ❌ Error while pausing ähnelt.
        /// </summary>
        internal static string pauseError {
            get {
                return ResourceManager.GetString("pauseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⏸ Pausing, please be patient... ähnelt.
        /// </summary>
        internal static string pauseInProgress {
            get {
                return ResourceManager.GetString("pauseInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ℹ Nothing to Pause here, no Bulk Import running at the moment. ähnelt.
        /// </summary>
        internal static string pauseNoOp {
            get {
                return ResourceManager.GetString("pauseNoOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ✅ Successfully paused! ähnelt.
        /// </summary>
        internal static string pauseSuccessful {
            get {
                return ResourceManager.GetString("pauseSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ⚠ Attention! ⚠ The Bot is missing permissions in the PokeNav mod-channel:\n\t{0} View Channel\n\t{1} Send Messages\n\t{2} Add Reactions (recommended but optional)\n\t{3} View message history (for ambiguous edits)\nMake sure to grant the neccessary permissions for the bot for &lt;#{4}&gt;. ähnelt.
        /// </summary>
        internal static string promptMissingPerms {
            get {
                return ResourceManager.GetString("promptMissingPerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ▶ Continuing... ähnelt.
        /// </summary>
        internal static string resume {
            get {
                return ResourceManager.GetString("resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ℹ Bulk import is already running, no need to resume. ähnelt.
        /// </summary>
        internal static string resumeAlreadyRunning {
            get {
                return ResourceManager.GetString("resumeAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ℹ No data to import present. ähnelt.
        /// </summary>
        internal static string resumeNoOp {
            get {
                return ResourceManager.GetString("resumeNoOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you really sure? The bot will need manual restart if you do this! ähnelt.
        /// </summary>
        internal static string sure {
            get {
                return ResourceManager.GetString("sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \nThis is the test instance. ähnelt.
        /// </summary>
        internal static string testInstance {
            get {
                return ResourceManager.GetString("testInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ❌ This interaction is not allowed in this context. ❌\n{0} ähnelt.
        /// </summary>
        internal static string unmetPrecondition {
            get {
                return ResourceManager.GetString("unmetPrecondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes i am ähnelt.
        /// </summary>
        internal static string yesIAm {
            get {
                return ResourceManager.GetString("yesIAm", resourceCulture);
            }
        }
    }
}
